### ISSUE TITLE
The method 'handleSystemMessage' isn't defined for the class 'PaintingBinding'.

### ISSUE THREAD

**Issue by d4dd4r** [material-foundation/google-fonts-flutter#19]
Hello! I'm trying to use this package.
But when I'm using it I got an error.

```
Compiler message:
../flutter/.pub-cache/hosted/pub.dartlang.org/google_fonts-0.2.0/lib/src/google_fonts_base.dart:105:28: Error: The method 'handleSystemMessage' isn't defined for the class 'PaintingBinding'.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../flutter/packages/flutter/lib/src/painting/binding.dart').
Try correcting the name to the name of an existing method, or defining a method named 'handleSystemMessage'.
  PaintingBinding.instance.handleSystemMessage({'type': 'fontsChange'});
                           ^^^^^^^^^^^^^^^^^^^
```

Am I doing something wrong?

My pubspec
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

My tools verisons
```
my_app $ flutter --version
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```
